### PR TITLE
Remove reference to Google's DNS servers

### PR DESCRIPTION
**Pull request by ariddell**
Per discussion on #429 (after the merge). This project is about encouraging users to run services themselves and not rely on for-profit corporations such as Google.

### CODE REVIEW

**Comment by Friz-zy** [comment]
The problem is that if you run your own dns server on the host for vpn it will use default dns of your provider if i'm right remember.
For example, in ex-USSR like Russia we can trust google dns much more than default dns providers...
Another example: in Kazakhstan government want create MITM for all country traffic...
For me Google better than NSA or local analog.

**Comment by neuhaus** [comment]
If you run your own resolver it queries the root servers directly unless you configure it to use your ISPs resolver as uplink.

**Comment by Friz-zy** [comment]
Oh, nice then!
Thanks for advice

**Comment by ariddell** [comment]
This is the wrong PR @neuhaus -- I accidentally created this on my own fork, someone needs to merge sovereign/sovereign#436

**Pull request merged**
